[package]
name = "ps1_boot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
sdl2 = "0.37.0"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "gltest"
path = "src/gltest.rs"
